# CMake generated Testfile for 
# Source directory: C:/Development/op3d_active/dirent-1.23.2
# Build directory: C:/Development/op3d_active/dirent-1.23.2/msvc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t-compile "C:/Development/op3d_active/dirent-1.23.2/msvc/Debug/t-compile.exe")
  set_tests_properties(t-compile PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;49;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t-compile "C:/Development/op3d_active/dirent-1.23.2/msvc/Release/t-compile.exe")
  set_tests_properties(t-compile PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;49;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t-compile "C:/Development/op3d_active/dirent-1.23.2/msvc/MinSizeRel/t-compile.exe")
  set_tests_properties(t-compile PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;49;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t-compile "C:/Development/op3d_active/dirent-1.23.2/msvc/RelWithDebInfo/t-compile.exe")
  set_tests_properties(t-compile PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;49;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
else()
  add_test(t-compile NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t-dirent "C:/Development/op3d_active/dirent-1.23.2/msvc/Debug/t-dirent.exe")
  set_tests_properties(t-dirent PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;50;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t-dirent "C:/Development/op3d_active/dirent-1.23.2/msvc/Release/t-dirent.exe")
  set_tests_properties(t-dirent PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;50;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t-dirent "C:/Development/op3d_active/dirent-1.23.2/msvc/MinSizeRel/t-dirent.exe")
  set_tests_properties(t-dirent PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;50;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t-dirent "C:/Development/op3d_active/dirent-1.23.2/msvc/RelWithDebInfo/t-dirent.exe")
  set_tests_properties(t-dirent PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;50;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
else()
  add_test(t-dirent NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t-scandir "C:/Development/op3d_active/dirent-1.23.2/msvc/Debug/t-scandir.exe")
  set_tests_properties(t-scandir PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;51;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t-scandir "C:/Development/op3d_active/dirent-1.23.2/msvc/Release/t-scandir.exe")
  set_tests_properties(t-scandir PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;51;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t-scandir "C:/Development/op3d_active/dirent-1.23.2/msvc/MinSizeRel/t-scandir.exe")
  set_tests_properties(t-scandir PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;51;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t-scandir "C:/Development/op3d_active/dirent-1.23.2/msvc/RelWithDebInfo/t-scandir.exe")
  set_tests_properties(t-scandir PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;51;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
else()
  add_test(t-scandir NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t-unicode "C:/Development/op3d_active/dirent-1.23.2/msvc/Debug/t-unicode.exe")
  set_tests_properties(t-unicode PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;52;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t-unicode "C:/Development/op3d_active/dirent-1.23.2/msvc/Release/t-unicode.exe")
  set_tests_properties(t-unicode PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;52;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t-unicode "C:/Development/op3d_active/dirent-1.23.2/msvc/MinSizeRel/t-unicode.exe")
  set_tests_properties(t-unicode PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;52;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t-unicode "C:/Development/op3d_active/dirent-1.23.2/msvc/RelWithDebInfo/t-unicode.exe")
  set_tests_properties(t-unicode PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;52;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
else()
  add_test(t-unicode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t-cplusplus "C:/Development/op3d_active/dirent-1.23.2/msvc/Debug/t-cplusplus.exe")
  set_tests_properties(t-cplusplus PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;53;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t-cplusplus "C:/Development/op3d_active/dirent-1.23.2/msvc/Release/t-cplusplus.exe")
  set_tests_properties(t-cplusplus PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;53;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t-cplusplus "C:/Development/op3d_active/dirent-1.23.2/msvc/MinSizeRel/t-cplusplus.exe")
  set_tests_properties(t-cplusplus PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;53;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t-cplusplus "C:/Development/op3d_active/dirent-1.23.2/msvc/RelWithDebInfo/t-cplusplus.exe")
  set_tests_properties(t-cplusplus PROPERTIES  WORKING_DIRECTORY "C:/Development/op3d_active/dirent-1.23.2" _BACKTRACE_TRIPLES "C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;45;add_test;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;53;add_test_executable;C:/Development/op3d_active/dirent-1.23.2/CMakeLists.txt;0;")
else()
  add_test(t-cplusplus NOT_AVAILABLE)
endif()
